---
- hosts: 172.31.36.60
  tasks:
    - name: saunil
      shell: rm -rf /var/www/html/*

    - name: cleaning files
      shell: rm -rf ~/test1

    - name: pull
      shell: git clone https://github.com/Saumil343/test1.git

    - name: copy
      shell: cp -r ~/test1 /var/www/html/
      
    - name: service1
      service:
        name: httpd
        state: restarted
   
